// Generated by CoffeeScript 1.9.3
(function() {
  angular.module('judge', []).controller('problemController', function($scope, $http) {
    $http.get('/getProblems').success(function(res) {
      return $scope.controller.problems = res;
    });
  }).controller('codeController', function($scope) {
    this.name = $scope.problem.id;
    console.log(this.name + '-editor');
  }).directive('afterRender', function() {
    return {
      link: function(scope, ele, attr) {
        var editor;
        editor = ace.edit(ele[0]);
        $(ele).height(400);
        editor.setTheme("ace/theme/tomorrow_night_bright");
        editor.getSession().setMode("ace/mode/python");
        $.get('code/' + scope.problem.id, function(data) {
          editor.setValue(data);
          editor.gotoLine(0);
          return editor.setOptions({
            fontSize: '18px'
          });
        });
      }
    };
  });

}).call(this);
