// Generated by CoffeeScript 1.9.3
(function() {
  var wsuri;

  wsuri = "ws://localhost:3000/ws/";

  this.ws = null;

  this.connect = function() {
    var err;
    try {
      this.ws = new WebSocket(wsuri);
      this.ws.onopen = function() {
        return console.log("connected to", wsuri);
      };
      this.ws.onmessage = function(evt) {
        var reader;
        reader = new FileReader();
        reader.onload = function(evt) {
          var data;
          data = JSON.parse(evt.target.result);
          return updateStatus(data);
        };
        return reader.readAsText(evt.data);
      };
      return this.ws.onclose = function() {
        return console.log("closed");
      };
    } catch (_error) {
      err = _error;
      console.log("can't connect to", wsuri);
      return console.log("error message:", err.message);
    }
  };

}).call(this);
