// Generated by CoffeeScript 1.9.0
(function() {
  var root;

  root = window.App;

  root.wsuri = "ws://140.112.18.226:3000/ws/";

  root.ws = null;

  root.connect = function() {
    var err, ws;
    try {
      ws = new WebSocket(root.wsuri);
    } catch (_error) {
      err = _error;
      console.log("can't connect to", root.wsuri);
      console.log("error message:", err.message);
    }
    ws.onopen = function() {
      return console.log("connected to", root.wsurl);
    };
    ws.onmessage = function(evt) {
      var reader;
      reader = new FileReader();
      reader.onload = function(evt) {
        var data;
        data = JSON.parse(evt.target.result);
        return root.scene.updateStatus(data);
      };
      return reader.readAsText(evt.data);
    };
    ws.onclose = function() {
      return console.log("closed");
    };
    ws.sendJSON = function(obj) {
      return this.send(JSON.stringify(obj));
    };
    return root.ws = ws;
  };

}).call(this);
