// Generated by CoffeeScript 1.9.0
(function() {
  document.addEventListener('keydown', function(event) {
    if (event.keyCode === 37) {
      return console.log('left');
    } else if (event.keyCode === 39) {
      return console.log('right');
    } else if (event.keyCode === 38) {
      return console.log('up');
    } else if (event.keyCode === 40) {
      return console.log('down');
    }
  });

  document.addEventListener('keyup', function(event) {
    if (event.keyCode === 37) {
      return console.log('left is up');
    } else if (event.keyCode === 39) {
      return console.log('right is up');
    } else if (event.keyCode === 38) {
      return console.log('up is up');
    } else if (event.keyCode === 40) {
      return console.log('down is up');
    }
  });

}).call(this);
