// Generated by CoffeeScript 1.9.3
(function() {
  var keyFlag, keyMap, root;

  root = window.App;

  keyFlag = {
    37: false,
    38: false,
    39: false,
    40: false,
    72: false,
    74: false,
    75: false,
    76: false
  };

  keyMap = {
    37: 'left',
    38: 'up',
    39: 'right',
    40: 'down',
    72: 'h',
    74: 'j',
    75: 'k',
    76: 'l'
  };

  $(function() {
    root.sendControl = function() {
      var C, D, E, omegaZ, thetaX, thetaY, vZ;
      C = 20.0 * Math.PI / 180;
      D = 30.0 * Math.PI / 180;
      E = 1;
      thetaX = -C * keyFlag[38] + C * keyFlag[40];
      thetaY = -C * keyFlag[37] + C * keyFlag[39];
      omegaZ = D * keyFlag[72] - D * keyFlag[76];
      vZ = -E * keyFlag[74] + E * keyFlag[75];
      console.log(thetaX);
      return this.ws.sendJSON({
        action: 'control',
        args: [vZ, thetaX, thetaY, omegaZ]
      });
    };
    document.addEventListener('keydown', function(event) {
      var k;
      k = event.keyCode;
      if (!(k in keyMap)) {
        return;
      }
      if (keyFlag[k]) {
        return;
      }
      keyFlag[k] = true;
      return root.sendControl();
    });
    return document.addEventListener('keyup', function(event) {
      var k;
      k = event.keyCode;
      if (!(k in keyMap)) {
        return;
      }
      keyFlag[k] = false;
      return root.sendControl();
    });
  });

}).call(this);
