// Generated by CoffeeScript 1.9.3
(function() {
  var keyFlag, keyMap, root;

  root = window.App;

  keyFlag = {
    37: false,
    38: false,
    39: false,
    40: false
  };

  keyMap = {
    37: 'left',
    38: 'up',
    39: 'right',
    40: 'down'
  };

  $(function() {
    root.sendControl = function() {
      var C, thetaX, thetaY;
      C = 20.0 * Math.PI / 180;
      thetaX = -C * keyFlag[38] + C * keyFlag[40];
      thetaY = -C * keyFlag[37] + C * keyFlag[39];
      console.log(thetaX);
      return this.ws.sendJSON({
        action: 'control',
        args: [0, thetaX, thetaY, 0]
      });
    };
    document.addEventListener('keydown', function(event) {
      var k;
      k = event.keyCode;
      if (keyFlag[k]) {
        return;
      }
      keyFlag[k] = true;
      return root.sendControl();
    });
    return document.addEventListener('keyup', function(event) {
      var k;
      k = event.keyCode;
      keyFlag[k] = false;
      return root.sendControl();
    });
  });

}).call(this);
