// Generated by CoffeeScript 1.9.3
(function() {
  var root;

  window.App = {};

  root = window.App;

  $(function(event) {
    var c, fn, i, len, ref;
    root.connect();
    root.scene.start();
    $('#start-btn').click(function() {
      return root.ws.sendJSON({
        action: 'start',
        args: []
      });
    });
    $('#reset-btn').click(function() {
      return root.scene.controls.reset();
    });
    ref = ['P', 'I', 'D'];
    fn = function(cc) {
      return $('#range-' + c).change(function() {
        $(this).prev().text($(this).val() + '%');
        root.ws.sendJSON({
          action: 'tweak',
          args: [cc, parseFloat($(this).val()) * 0.01]
        });
      });
    };
    for (i = 0, len = ref.length; i < len; i++) {
      c = ref[i];
      fn(c);
    }
    return $('#switch-panel>li').click(function() {
      var me;
      me = $(this);
      $(this).siblings().removeClass('active');
      $(this).addClass('active');
      return root.changeChart(me.attr('data'));
    });
  });

}).call(this);
