// Generated by CoffeeScript 1.9.3
(function() {
  var Range, root;

  window.App = {};

  root = window.App;

  Range = ace.require('ace/range').Range;

  $(window).on('beforeunload', function() {
    return root.ws.close();
  });

  $(function(event) {
    var c, editor, fn, i, len, ref;
    root.connect();
    root.connectPythonErrSocket();
    root.scene.start();
    $('#run-btn').click(function() {
      return root.sendCodeAndRun();
    });
    $('#start-btn').click(function() {
      root.ws.sendJSON({
        action: 'start',
        args: []
      });
      return root.clearChart();
    });
    $('#stop-btn').click(function() {
      $.post('/', {
        action: 'stop'
      });
      return root.ws.close();
    });
    $('#code-btn').click(function() {
      if (!root.codeLoaded) {
        return;
      }
      return $('#code-wrapper').show(200, function() {
        return $('#code-area textarea').focus();
      });
    });
    $('#reset-btn').click(function() {
      return root.scene.controls.reset();
    });
    ref = ['P', 'I', 'D'];
    fn = function(cc) {
      return $('#range-' + c).change(function() {
        $(this).prev().text($(this).val() + '%');
        root.ws.sendJSON({
          action: 'tweak',
          args: [cc, parseFloat($(this).val()) * 0.01]
        });
      }).focus(function() {
        return $(this).blur();
      });
    };
    for (i = 0, len = ref.length; i < len; i++) {
      c = ref[i];
      fn(c);
    }
    $('#switch-panel>li').click(function() {
      var me;
      me = $(this);
      $(this).siblings().removeClass('active');
      $(this).addClass('active');
      return root.changeChart(me.attr('data'));
    });
    editor = ace.edit('code-area');
    editor.setTheme("ace/theme/tomorrow_night_bright");
    editor.getSession().setMode("ace/mode/python");
    root.editor = editor;
    root.sendCodeAndRun = function() {
      $.post('/runCode', {
        code: root.editor.getValue()
      });
      root.ws.open();
      $('#code-wrapper').hide();
      root.clearMarkers();
      return Materialize.toast('The program is starting!', 2000);
    };
    root.showDronePanel = function() {
      return $('#drone-control-panel').show().removeClass('animated bounceOut').addClass('animated bounceIn');
    };
    root.hideDronePanel = function() {
      return $('#drone-control-panel').removeClass('animated bounceIn').addClass('animated bounceOut').one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend', function() {
        var me;
        me = $('#drone-control-panel');
        if (me.hasClass('bounceOut')) {
          return me.hide();
        }
      });
    };
    root.onSocketConnected = function() {
      return root.showDronePanel();
    };
    root.onSocketClosed = function() {
      return root.hideDronePanel();
    };
    root.clearMarkers = function() {
      var markers;
      markers = root.editor.session.getMarkers();
      window.a = markers;
      return Object.keys(markers).map(function(x) {
        return markers[x];
      }).filter(function(x) {
        return x.clazz === 'ace-editor-error';
      }).forEach(function(x) {
        console.log(x);
        return root.editor.session.removeMarker(x.id);
      });
    };
    root.onPythonError = function(err, flag) {
      var ln, mat, pat;
      err = err.replace(/\n/g, '<br>');
      $('#error-text').html(err);
      if (!flag) {
        $('#error-text').removeClass('red').addClass('green');
        return;
      }
      $('#error-text').removeClass('green').addClass('red');
      pat = /mypid.py", line (\d+)/g;
      mat = pat.exec(err);
      if (mat) {
        ln = mat[1] - 1;
        root.errorLine = ln;
        root.editor.session.addMarker(new Range(ln, 0, ln, 100), "ace-editor-error", "fullLine", false);
      }
      return $('#code-wrapper').show(200);
    };
    $.get('/mypid.py', function(data) {
      root.editor.setValue(data);
      root.editor.gotoLine(0, 0, true);
      return root.codeLoaded = true;
    });
    $('#return-btn').click(function() {
      console.log(123);
      return $('#code-wrapper').hide(200);
    });
    return $('#code-run-btn').click(function() {
      return root.sendCodeAndRun();
    });
  });

}).call(this);
