// Generated by CoffeeScript 1.9.0
(function() {
  document.addEventListener("DOMContentLoaded", function(event) {
    connect();
    return $('#start-btn').click(function() {
      return ws.send(JSON.stringify({
        action: 'start'
      }));
    });
  });

}).call(this);
