// Generated by CoffeeScript 1.9.0
(function() {
  $(function() {
    $(document).ready(function() {
      Highcharts.setOptions({
        global: {
          useUTC: false
        }
      });
      $('#container').highcharts('StockChart', {
        chart: {
          marginRight: 10,
          events: {
            load: function() {
              window.series = this.series[0];
              return console.log(123);
            }
          }
        },
        xAxis: {
          type: 'datetime',
          tickPixelInterval: 150,
          minRange: 10000
        },
        yAxis: {
          title: {
            text: 'Value'
          },
          plotLines: [
            {
              value: 0,
              width: 1,
              color: '#808080'
            }
          ]
        },
        tooltip: {
          formatter: function() {
            return '<b>' + this.series.name + '</b><br/>' + Highcharts.dateFormat('%Y-%m-%d %H:%M:%S', this.x) + '<br/>' + Highcharts.numberFormat(this.y, 2);
          }
        },
        legend: {
          enabled: false
        },
        exporting: {
          enabled: false
        },
        series: [
          {
            name: 'Random data',
            data: [0]
          }
        ]
      });
    });
  });

}).call(this);
