// Generated by CoffeeScript 1.9.3
(function() {
  var root;

  root = window.App;

  $(function() {
    var chart, dataLength, dps, updateInterval, xVal, yVal;
    dps = [[], [], []];
    chart = new CanvasJS.Chart("plot-wrapper", {
      data: [
        {
          markerType: "none",
          type: "line",
          dataPoints: dps[0],
          legendText: "Angle-x",
          showInLegend: true
        }, {
          markerType: "none",
          type: "line",
          dataPoints: dps[1],
          legendText: "Angle-y",
          showInLegend: true
        }, {
          markerType: "none",
          type: "line",
          dataPoints: dps[2],
          legendText: "Angle-z",
          showInLegend: true
        }
      ],
      axisX: {
        valueFormatString: "ss.fff"
      }
    });
    xVal = 0;
    yVal = 100;
    updateInterval = 20;
    dataLength = 500;
    return root.updateChart = function(arr) {
      var cur, i, j;
      cur = new Date();
      for (i = j = 0; j <= 2; i = ++j) {
        dps[i].push({
          x: cur,
          y: arr[i]
        });
      }
      return chart.render();
    };
  });

}).call(this);
